modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="metamobs"
version="1.0.0"
displayName="MetaMobs"
credits="This mod was made with Mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Sapphire, MCreator"

[[dependencies.metamobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




